name: Image Testing Build and Release

on:
  push:
    branches:
      - "main"
    paths:
      - 'alpine/**/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and push Docker image for Alpine 3.14
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: alpine/3.14/Dockerfile
        context: .
        push: true
        tags: ghcr.io/mtharpe/alpine:3.14

    - name: Build and push Docker image for Alpine 3.15
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: alpine/3.15/Dockerfile
        context: .
        push: true
        tags: ghcr.io/mtharpe/alpine:3.15

    - name: Build and push Docker image for Alpine 3.16
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: alpine/3.16/Dockerfile
        context: .
        push: true
        tags: ghcr.io/mtharpe/alpine:3.16

    - name: Build and push Docker image for Alpine Latest
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: alpine/latest/Dockerfile
        context: .
        push: true
        tags: ghcr.io/mtharpe/alpine:latest