name: Image Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Fedora Docker images
      run: cd fedora && ./build.sh
    - name: Build Ubuntu Docker images
      run: cd ubuntu && ./build.sh