name: Image Testing Build and Release

on:
  push:
    paths:
      - '**/**/Dockerfile'
  pull_request:
    paths:
      - '**/**/Dockerfile'
  schedule:
    - cron '0 * * * 0-6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and push Docker image for Fedora 33
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: fedora/33/Dockerfile
        context: .
        push: true
        tags: ghcr.io/mtharpe/fedora:33

    - name: Build and push Docker image for Fedora 34
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: fedora/34/Dockerfile
        context: .
        push: true
        tags: ghcr.io/mtharpe/fedora:34

    - name: Build and push Docker image for Fedora 35
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: fedora/35/Dockerfile
        context: .
        push: true
        tags: ghcr.io/mtharpe/fedora:35

    - name: Build and push Docker image for Fedora 36
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: fedora/36/Dockerfile
        context: .
        push: true
        tags: ghcr.io/mtharpe/fedora:36

    - name: Build and push Docker image for Fedora Latest
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: fedora/latest/Dockerfile
        context: .
        push: true
        tags: ghcr.io/mtharpe/fedora:latest

    - name: Build and push Docker image for Ubuntu 18.04
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: ubuntu/18.04/Dockerfile
        context: .
        push: true
        tags: ghcr.io/mtharpe/ubuntu18.04:main

    - name: Build and push Docker image for Ubuntu 20.04
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: ubuntu/20.04/Dockerfile
        context: .
        push: true
        tags: ghcr.io/mtharpe/ubuntu:20.04

    - name: Build and push Docker image for Ubuntu 21.04
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: ubuntu/21.04/Dockerfile
        context: .
        push: true
        tags: ghcr.io/mtharpe/ubuntu:21.04

    - name: Build and push Docker image for Ubuntu Latest
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: ubuntu/latest/Dockerfile
        context: .
        push: true
        tags: ghcr.io/mtharpe/ubuntu:latest

    - name: Build and push Docker image for Alpine 3.14
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: alpine/3.14/Dockerfile
        context: .
        push: true
        tags: ghcr.io/mtharpe/alpine:3.14

    - name: Build and push Docker image for Alpine 3.15
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: alpine/3.15/Dockerfile
        context: .
        push: true
        tags: ghcr.io/mtharpe/alpine:3.15

    - name: Build and push Docker image for Alpine 3.16
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: alpine/3.16/Dockerfile
        context: .
        push: true
        tags: ghcr.io/mtharpe/alpine:3.16

    - name: Build and push Docker image for Alpine Latest
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: alpine/latest/Dockerfile
        context: .
        push: true
        tags: ghcr.io/mtharpe/alpine:latest