name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Fedora Docker images
      run: docker build -t fedora33:base fedora/33/Dockerfile
    - name: Build Fedora Docker images
      run: docker build -t fedora34:base fedora/34/Dockerfile
    - name: Build Fedora Docker images
      run: docker build -t fedora35:base fedora/35/Dockerfile
