name: Image Testing Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and push Docker image for Fedora 33
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: fedora/33/Dockerfile
        context: .
        push: true
        tags: ghcr.io/mtharpe/fedora33:main

    - name: Build and push Docker image for Fedora 34
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: fedora/34/Dockerfile
        context: .
        push: true
        tags: ghcr.io/mtharpe/fedora34:main

    - name: Build and push Docker image for Fedora 35
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: fedora/35/Dockerfile
        context: .
        push: true
        tags: ghcr.io/mtharpe/fedora35:main

    - name: Build and push Docker image for Fedora 36
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: fedora/36/Dockerfile
        context: .
        push: true
        tags: ghcr.io/mtharpe/fedora36:main

    - name: Build and push Docker image for Ubuntu 18.04
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: ubuntu/18.04/Dockerfile
        context: .
        push: true
        tags: ghcr.io/mtharpe/ubuntu18.04:main

    - name: Build and push Docker image for Ubuntu 20.04
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: ubuntu/20.04/Dockerfile
        context: .
        push: true
        tags: ghcr.io/mtharpe/ubuntu20.04:main

    - name: Build and push Docker image for Ubuntu 21.04
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: ubuntu/21.04/Dockerfile
        context: .
        push: true
        tags: ghcr.io/mtharpe/ubuntu21.04:main

    - name: Build and push Docker image for Ubuntu 22.04
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: ubuntu/22.04/Dockerfile
        context: .
        push: true
        tags: ghcr.io/mtharpe/ubuntu22.04:main