name: Image Linting

on:
  push:
    branches:
      - "main"
    #paths:
    #  - '**/**/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Linting
      uses: hadolint/hadolint-action@v2.0.0
      with:
        dockerfile: Dockerfile
        recursive: true
        ignore: DL3018,DL3007,DL3059,DL3041,DL3008
