name: Image Testing Build and Release

on:
  push:
    branches:
      - "main"
    paths:
      - 'manjaro/**/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and push Docker image for Manjaro Latest
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: manjaro/latest/Dockerfile
        context: .
        push: true
        tags: ghcr.io/mtharpe/manjaro:latest